class OutPassModel {
  final String? id; // Nullable if generated by Supabase
  final String studentId;
  final String studentName;
  final String destination;
  final DateTime departureTime;
  final String status;

  OutPassModel({
    this.id,
    required this.studentId,
    required this.studentName,
    required this.destination,
    required this.departureTime,
    required this.status,
  });

  factory OutPassModel.fromJson(Map<String, dynamic> json) => OutPassModel(
    id: json['id'] as String?,
    studentId: json['student_id'] as String,
    studentName: json['student_name'] as String,
    destination: json['destination'] as String,
    departureTime: DateTime.parse(json['departure_time'] as String),
    status: json['status'] as String,
  );

  Map<String, dynamic> toJson() => {
    'student_id': studentId,
    'student_name': studentName,
    'destination': destination,
    'departure_time': departureTime.toIso8601String(),
    'status': status,
  };
}